packages:
  - 'apps/bulletproof-vue-vite'
  - 'apps/bulletproof-nuxt'
  - 'apps/bulletproof-nuxt-regle'
  - 'apps/bulletproof-nuxt-tanstack-form'
  - 'apps/bulletproof-nuxt-formwerk'
  - 'apps/bulletproof-nuxt-pinia-colada'
