export { default as Table } from './Table.vue'
export { default as TableElement } from './TableElement.vue'
export { default as TableHeader } from './TableHeader.vue'
export { default as TableBody } from './TableBody.vue'
export { default as TableRow } from './TableRow.vue'
export { default as TableCell } from './TableCell.vue'
export { default as TableHead } from './TableHead.vue'
export { default as TablePagination } from './TablePagination.vue'
export { default as Pagination } from './Pagination.vue'
export { default as PaginationContent } from './PaginationContent.vue'
export { default as PaginationLink } from './PaginationLink.vue'
export { default as PaginationNext } from './PaginationNext.vue'
export { default as PaginationPrevious } from './PaginationPrevious.vue'
export { default as PaginationItem } from './PaginationItem.vue'
export { default as PaginationEllipsis } from './PaginationEllipsis.vue'

export * from './TablePagination.vue'
