export { default as Table, type TableColumn } from './table.vue'
export { default as TableElement } from './table-element.vue'
export { default as TableHeader } from './table-header.vue'
export { default as TableBody } from './table-body.vue'
export { default as TableRow } from './table-row.vue'
export { default as TableCell } from './table-cell.vue'
export { default as TableHead } from './table-head.vue'
export { default as TablePagination } from './table-pagination.vue'
export { default as Pagination } from './pagination.vue'
export { default as PaginationContent } from './pagination-content.vue'
export { default as PaginationLink } from './pagination-link.vue'
export { default as PaginationNext } from './pagination-next.vue'
export { default as PaginationPrevious } from './pagination-previous.vue'
export { default as PaginationItem } from './pagination-item.vue'
export { default as PaginationEllipsis } from './pagination-ellipsis.vue'

export * from './table-pagination.vue'
